### ISSUE TITLE
Different content between 1.18 release tag and release branch

### ISSUE THREAD

**Issue by harper1011** [kubernetes/cloud-provider-openstack#1184]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind question

**What happened**:
There are different content between 1.18 release tag and release branch

**How to reproduce it**:
Please check: https://github.com/kubernetes/cloud-provider-openstack/compare/v1.18.0...release-1.18

**Anything else we need to know?**:
So it seems there will be further release of v1.18.1 soon? If so, could we know the estimated schedule?

**Comment by ramineni** [comment]
@harper1011 you are right, we did couple of backports to 1.18 branch and did publish docker images with new changes https://hub.docker.com/r/k8scloudprovider/openstack-cloud-controller-manager , but ya tag corresponds to base 1.18 release.

/cc @lingxiankong

**Comment by lingxiankong** [comment]
@ramineni is right, we have backported several commits to the v1.18 branch but didn't update the tag.

@harper1011 We don't do minor releases for the repo, but only upload the docker images when there is PR backported, because we believe the docker images are the artifacts that people need for the deployment. That's why you can see image tags such as v1.18.2 in https://hub.docker.com/r/k8scloudprovider/openstack-cloud-controller-manager/tags
