### ISSUE TITLE
[All] docker images with latest tags not getting pushed periodically

### ISSUE THREAD

**Issue by ramineni** [kubernetes/cloud-provider-openstack#1361]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
latest images of plugins are not getting published on docker Hub . 
https://hub.docker.com/r/k8scloudprovider/openstack-cloud-controller-manager/tags?page=1&ordering=last_updated

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
I tried to use `latest ` tag and it's able to find the image
so is it the openlab who should submit this change or how can we do in this repo？ just curious

**Comment by ramineni** [comment]
@jichenjc I raised the issue for tracking purpose, mostly this needs to be fixed in openlab only.

**Comment by lingxiankong** [comment]
In the job cloud-provider-openstack-acceptance-test-e2e-conformance, all the latest tag images are uploaded to huawei container image registry rather than docker hub, this change was made several months ago because docker hub is not accessible in China anymore.

openlab guys said they have a job to sync images to docker hub, will double check with them for what happened.

**Comment by ramineni** [comment]
@lingxiankong Got it. Thanks for the update.

**Comment by lingxiankong** [comment]
The latest images should be updated now. Please have a check and close this issue if OK.

**Comment by ramineni** [comment]
@lingxiankong Thanks. Its updated now.

/close
