### ISSUE TITLE
[cinder-csi-plugin] possibility to set bytes-per-inode and inode size on pv

### ISSUE THREAD

**Issue by VVvKamper** [kubernetes/cloud-provider-openstack#1428]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:

We are trying to store a lot of small files on the disk and default (1 inode per 16 KB) fs settings is not suitable for such task

**What you expected to happen**:

Some parameters on the storage class to specify args for `mkfs.*` comand i.e. `-i` (bytes per inode), `-I` (inode size) and `-O inline_data` (enable data inlining) or maybe even ability to add arbitrary options.

Or maybe some annotations for pvc to specify this options per volume.

**How to reproduce it**:

**Anything else we need to know?**:

As i understand `cinder-csi-plugin` uses [this code](https://github.com/kubernetes/utils/blob/master/mount/mount_linux.go#L356-L367) to format and mount fs on pv creation and there is no interface to add additional args for `mkfs.*`. I would be happy to try to provide PR for this feature but i'm not sure if it even possible to make such change in this upstream library. So my question is - do you think this feature is good for the project or it's too much burden to implement?

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by jichenjc** [comment]
@VVvKamper looks like you are referring to k8s code instead of CPO code
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/nodeserver.go#L397
called to format the disk but seems we can do nothing because as you pointed out, there is no way for that code  
to accept param except the fs type .. maybe you can post this question to k8s repo as well to get some opinion
? if turn out k8s support and CPO doesn't provide those options, I think reasonable to add at CPO side... thanks

**Comment by ramineni** [comment]
@VVvKamper there is 'mountOptions' available while creating storageclass , https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#storageclass-v1-storage-k8s-io, you can add extra options , those should be passed to the call.

**Comment by jichenjc** [comment]
@ramineni I guess the ask is for mkfs option not for the mount option ...

**Comment by ramineni** [comment]
/close
Not in scope of this repo, pls raise issue in diff repo as suggested above.
