### ISSUE TITLE
[manila-csi-plugin] Cannot customize csi driver options

### ISSUE THREAD

**Issue by jjdiazgarcia** [kubernetes/cloud-provider-openstack#1893]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
I can't enable fsGroup policy for CSIDriver

**What you expected to happen**:
Features supported by Kubernetes CSI are available to customize CSIDriver deployed using helm template defined in https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/manila-csi-plugin/templates/csidriver.yaml

**How to reproduce it**:
Deploy CSIDriver using template https://github.com/kubernetes/cloud-provider-openstack/blob/master/charts/manila-csi-plugin/templates/csidriver.yaml

There is no option to configure fsGroup policy https://kubernetes-csi.github.io/docs/support-fsgroup.html#supported-modes

**Anything else we need to know?**:
I have tried to modify CSIDriver manually and fsGroup policy feature works fine but there is no way to configure it to be deployed using templates.

As I have tested it manually and it works, I would say it is possible to modify helm template to allow enabling options defined by Kubernetes CSI.

If you agree, I can create the PR to allow customising csidriver.

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: N/A
- OpenStack version: N/A
- Others: N/A

**Comment by gouthampacha** [comment]
Hi @jjdiazgarcia; thank you for raising this issue. IMHO, and you may be aware, support for fsGroups with NAS based PVs is hard to implement (for one, the NAS server and the clients need to share the same id mapping for things to work as expected). Do you intend to allow an override so that we can set the fsGroupPolicy to None (and thereby prevent the recursive chmod/chown by kubelet)? 

@fmount is fixing the OpenShift manila CSI operator to plumb this capability into the CSIDriver [[1]](https://github.com/openshift/csi-driver-manila-operator/pull/142). He's pursuing a similar fix here upstream [[2]](https://github.com/fmount/cloud-provider-openstack/commit/09f7ad760fb02287e545afd589edecc68ab72b12). Would this satisfy your needs?

I'm also curious what storage is behind manila in your deployment. Thanks :)

[1] https://github.com/openshift/csi-driver-manila-operator/pull/142 
[2] https://github.com/fmount/cloud-provider-openstack/commit/09f7ad760fb02287e545afd589edecc68ab72b12

**Comment by jjdiazgarcia** [comment]
Hello @gouthampacha 
Thanks so much for your quick response.

What I have planned to do is to allow setting (or not) that property. If I am not wrong, if it is not set, by default, it is set to _None_ so we don't need to set it if it is not defined in values. Something similar to below code snippet.
`
{{- range .Values.shareProtocols }}
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ printf "%s.%s" .protocolSelector $.Values.driverName | lower }}
spec:
  attachRequired: false
  podInfoOnMount: false
  {{- if .fsGroupPolicy }}
  fsGroupPolicy: {{ .fsGroupPolicy }}
  {{- end }}
{{- end }}
`
What do you think about it?

I have had a look to the both links that are work in progress from @fmount and it looks like the second one [2](https://github.com/fmount/cloud-provider-openstack/commit/09f7ad760fb02287e545afd589edecc68ab72b12) would satisfy our needs.

Is there any deadline to merge it?

Regarding PR [1](https://github.com/openshift/csi-driver-manila-operator/pull/142), I am not using that component so that won't work for me. This is the driver I am using [kubernetes-csi/csi-driver-nfs](https://github.com/kubernetes-csi/csi-driver-nfs/tree/master/charts/v3.0.0/csi-driver-nfs/templates).

I don't really understand your question regarding storage behind manila so I can't answer you :(

Best regards

**Comment by jjdiazgarcia** [comment]
You are totally right @gouthampacha My bad.
Exactly, my needs are changing group owner without checking any other configuration. That is why I need to set policy to _File_

**Comment by gman0** [comment]
Hi @jjdiazgarcia! Thanks for the request. One of the reasons fsGroup policy is not exposed is because manila-csi supports only `ReadWriteMany` volume access mode at the moment. There could be multiple nodes trying to chmod the same volume, which would be  racy usually.

What storage backend are you using for this? Maybe it could work in your case, but in general we would need to deploy [external-attacher](https://github.com/kubernetes-csi/external-attacher) sidecar, which would solve the race condition as long as the volumes use `ReadWriteOnce` access mode.

So I'd suggest first working on (optionally) including the external-attacher in deployments, and then adding support for changing fsGroup policy. But maybe if we better understood your setup, and why you'd prefer `File` fsGroup policy mode instead of e.g. the default one that @gouthampacha has pointed out, your proposal could work too?

**Comment by jjdiazgarcia** [comment]
Hello @gman0 

I understand the reason.

I am not the owner of Openstack so I don't set up it but I would say we are using NetApp.

We have tried to use the default one policy and run and initContainer to change volumes permissions. Anyway, we are also using Gatekeeper and one of the policies is to avoid running containers using root user so, unfortunaterly, we can't use this approach.

Is it required to use external-attacher? Is not possible to expose fsGroupPolicy as a variable which default value is ReadWriteOnceWithFSType?

**Comment by jjdiazgarcia** [comment]
> @jjdiazgarcia Are you expecting the PVC to be mounted exclusively to a single Pod?

No, it could be mounted in more than one pod. We are using Gatekeeper so we control which users/groups are set in the deployment/statefulset/daemonset spec to avoid setting differente user for differente pods.

> Yes, I would say so. Otherwise you have no control over how many times the PVC is mounted, and how many times `chmod` is being run (by kubelet) in parallel for that volume. Unless your application is such that you don't care, but I think that would make this particular case pretty much an outlier, and usually for most of the use cases users would want only a single node chmod'ing.

We have several cases where volume is mounted in different nodes at the same time. Is it feasible for external-attacher. Anyway, we prefer to not add an additional piece to our system and that is why we suggest to expose _fsGroupPolicy_ as a variable.

**Comment by gman0** [comment]
@jjdiazgarcia thanks for the info, that makes it much clearer!

external-attacher (besides other things) is there to provide means of ensuring `ReadWriteOnce` and `ReadOnlyOnce` access modes, but your case is completely different since you still need RWX.

So I think this is good to go. There is already a PR for this, https://github.com/kubernetes/cloud-provider-openstack/pull/1894. Thanks @fmount for submitting it!

Just FYI, this is what is being done for every Pod mounting the volume:
* [SetUpAt](https://github.com/kubernetes/kubernetes/blob/451e1fa8bcff38b87504eebd414948e505526d01/pkg/volume/csi/csi_mounter.go#L279-L292)
* [SetVolumeOwnership](https://github.com/kubernetes/kubernetes/blob/451e1fa8bcff38b87504eebd414948e505526d01/pkg/volume/volume_linux.go#L40-L63)

The more files in a volume, and more Pods mounting that volume, the more load this will place on the storage backend, as well us slowing down pod start-up times. One way to mitigate this could be to have a dummy Pod just mounting the volume, and letting kubelet chmod its contents. Once that is finished, the application Pods could be deployed with [`fsGroupChangePolicy: "OnRootMismatch"`](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#configure-volume-permission-and-ownership-change-policy-for-pods) in their `securityContext` definitions.

**Comment by jjdiazgarcia** [comment]
Thanks so much for all the info and your help @gman0 and @gouthampacha 
I will keep having a look to that PR so we can use it one it is merged and a release in done.
Again, thanks so much.
