### ISSUE TITLE
[cinder-csi-plugin] spam against OpenStack APIs increases heavily if using livenessProbes

### ISSUE THREAD

**Issue by zetaab** [kubernetes/cloud-provider-openstack#1903]
**Is this a BUG REPORT or FEATURE REQUEST?**: 

/kind bug

**What happened**:

we are seeing HEAVY increasement in cinder API calls after 1.24.0.

With 1.23.0:
csi-cinder-controllerplugin made GET https://xxx:13776/ (cinder api in our case) calls 1/minute
csi-cinder-nodeplugin made GET https://xxx:13776/ (cinder api in our case) calls 0/minute

With 1.24.0:
csi-cinder-controllerplugin makes GET https://xxx:13776/ (cinder api in our case) calls 1/minute
csi-cinder-nodeplugin makes GET https://xxx:13776/ (cinder api in our case) calls 6/minute (once every 10 seconds)

<img width="1230" alt="Screenshot 2022-06-01 at 15 03 01" src="https://user-images.githubusercontent.com/22482503/171400000-93d60513-4d55-42b5-b15c-602e27033ac6.png">

Here is screenshot from OpenStack loadbalancer statistics. We started updating our clusters to 1.24.0 15 May (as you can see from the graphs). 

![Image Pasted at 2022-6-1 14-57](https://user-images.githubusercontent.com/22482503/171400812-9f1e05f1-bc64-440e-ad79-af3f9cfdafe5.png)

**What you expected to happen**:

I expect that csi-cinder-nodeplugin does not make GET call to cinder API root path every 10 seconds.

**How to reproduce it**:

Start 1.24.0 csi-cinder-nodeplugin with -v=6 and you can see the behaviour.

this happens every 10 seconds to each pod in each node:

```
I0601 11:52:31.267565       1 utils.go:88] [ID:12] GRPC call: /csi.v1.Identity/Probe
I0601 11:52:31.267580       1 utils.go:89] [ID:12] GRPC request: {}
I0601 11:52:31.267695       1 openstack_volumes.go:54] OpenStack Request URL: GET https://xxx:13776/
```

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by zetaab** [comment]
the row is this one https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/openstack/openstack_volumes.go#L54

and I think this is the caller https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/identityserver.go#L55

@chrigl

**Comment by chrigl** [comment]
The probe is called by the liveness sidecar. Are there any changes on those parameters? In our helm settings and plain manifests I don't find anything. I think the sidecar only calls out if there is a request to `/healthz`, so I probably not a thing of the sidecar version (2.5.0 vs 2.6.0). The helm chart defaults to 60s, while the plain yaml files only use 10s. So I would guess that this are the 10 seconds per pod, that you see. The controller-plugin defaults to 60s, which is what you also experience. Not sure why you now experience the increase, because settings didn't change since 1.20.0 🤷 

The call to openstack should be pretty lightweight, since it only the the "version" page is fetched and not a list of any volumes or such. I am on the fence with including downstream apis in a healthcheck, because of a couple of things:

Liveness would flip to false if for some reason cinder is not available (e.g. maintenance). This might cause in rotating the DS over and over again, without a real need for it. Pushing work on kubernetes where no work is todo.

Even with knowing that cinder is available, it doesn't tell us anything about whether or not volumes can be created or attached. There is logic to report failures in those facilities anyways.

When we would just return "Everything is fine" from `Probe`, the liveness sidecar reliably can say if our csi-plugin still exists and answers to requests. IMHO this is all we must report!? (gcp and aws also just return OK)
