### ISSUE TITLE
[occm] Multi region support

### ISSUE THREAD

**Issue by sergelogvinov** [kubernetes/cloud-provider-openstack#1924]
/kind feature

I am noticed that openstack-client supports multi-region config.  https://github.com/gophercloud/utils/blob/master/openstack/clientconfig/testing/clouds.yaml#L160-L171

What do you think to add the multi-region support in one OCCM, based on the config-file, after #1900 ?
If the config file has a regions tree, OCCM checks it at boot time and will watch the nodes in those regions.

**Comment by sergelogvinov** [comment]
Yep. You are right. I forgot about LB. 
I spoke about node/node-lifecycle only. 

For LB, it can be done by service annotation property... 

So, we can introduce it in steps.
Unfortunately, I do not have regional openstack with LB. It will be hard to test.

**Comment by sergelogvinov** [comment]
If the node uninitialized, we need to check all regions to fine the node.
If node has providerId, we can get the region name from it.

and if i right, we need to have ```go-client``` connection for each region.

**Comment by mikejoh** [comment]
> If the node uninitialized, we need to check all regions to fine the node. If node has providerId, we can get the region name from it.
> 
> and if i right, we need to have `go-client` connection for each region.

Correct! One compute `ServiceClient` per region basically. We're not completely done with our implementation, it's still in PoC mode, but so far everything looks good. We made sure to implement the `k8s.io/cloud-provider` [`InstancesV2`](https://github.com/kubernetes/cloud-provider/blob/04905862e78d299130f3a7a3dac05d7b40357964/cloud.go#L199-L212) interface which is slimmer and don't require as many queries against the underlying cloud APIs compared to the `Instances` interface.

As a side note: I know that there's a todo on implementing the V2 interface in the OCCM, which I think we could help out with!

**Comment by dulek** [comment]
> What about this feature ? This would clearly be needed in our use case where we have 3 Openstack standalone clusters and want to have kubernetes clusters stretched on top of them. This can be done but things get complicated since CCM can't handle more than 1 Openstack API endpoint and thus, this makes everything related to storage or LBs a hell.
> 
> Is this somewhere in the pipe or maybe there are some alternatives ? Any help would be gladly appreciated.

I don't think CPO was designed with that use case in mind and it might need a lot of work to get right. Happy to help with advice and reviews if you have some development resources to throw at this.

Interestingly - what's the use case to stretch K8s like that?

**Comment by Hybrid512** [comment]
> > What about this feature ? This would clearly be needed in our use case where we have 3 Openstack standalone clusters and want to have kubernetes clusters stretched on top of them. This can be done but things get complicated since CCM can't handle more than 1 Openstack API endpoint and thus, this makes everything related to storage or LBs a hell.
> > Is this somewhere in the pipe or maybe there are some alternatives ? Any help would be gladly appreciated.
> 
> I don't think CPO was designed with that use case in mind and it might need a lot of work to get right. Happy to help with advice and reviews if you have some development resources to throw at this.
> 
> Interestingly - what's the use case to stretch K8s like that?

In our case, the use cae is to have multi-AZ kubernetes clusters on top of multiple standalone Openstack clusters.
Basically, have one k8s cluster stretched on 3 different Openstack tenants, each in a standalone Openstack cluster.
Our k8s strategy is to have multiple k8s cluster for better ressource and security segmentation with a high level of automation.
Our Openstack clusters have routed networks but they are not streteched clusters themselves and they have their own dedicated storage that is not replicated to the other ones.
The idea behind that is that, since Openstack is the base supporting every k8s cluster we have, we rather secure Openstack operations by not stretching the Openstack itself (and instead, have multiple standalone clusters) so that failure (would it be hardware or security issue or even a simple human error) would impact only one AZ at a time and since our k8s clusters are stretched on top of these Openstack clusters, loosing an AZ would have nearly zero impact on the application layer.

However, I see there are PRs for this and we already try to help the best we can in this way so fingers crossed !

/remove-lifecycle rotten

**Comment by sergelogvinov** [comment]
Thank you for your feedback. 

I did research, and made the lab based on proxmox-vm. CCM/CSI work fine. One pvc-template resource works well on different AZ too, https://github.com/sergelogvinov/proxmox-csi-plugin 

I steal believe that I will repeat the same idea in this project. But only for CCM/CSI. 
I do not have LB in my openstack setup. And many loadbalancers/ingress-controllers do not work with GEO (region/zonal) balancing knowledge (serve traffic only in one zone/region).


make a vote 👍 please. it helps to contributors to understand how important this feature.
