### ISSUE TITLE
release 1.24.2 (record some additoinal info)

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#1925]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

following https://github.com/kubernetes/cloud-provider-openstack/blob/master/release-procedure.md

completed this step `git push upstream vX.Y.Z`

=> Github Actions will make the new docker images and make new draft release to repository.

where can I check this @zetaab @chrigl ? Thanks (I will copy your info into the doc as well)

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by chrigl** [comment]
The gh action is available in the Action tab -> Release CPO (https://github.com/kubernetes/cloud-provider-openstack/actions/workflows/release-cpo.yaml)

Since the release is a draft, it doesn't show up on the front-page, but when you click into the relases: https://github.com/kubernetes/cloud-provider-openstack/releases

**Comment by jichenjc** [comment]
the corresponding PR merged
