### ISSUE TITLE
[OCCM] Add support for multiple LBs for dual-stack k8s services

### ISSUE THREAD

**Issue by rastislavs** [kubernetes/cloud-provider-openstack#1937]
/kind feature

In https://github.com/kubernetes/cloud-provider-openstack/issues/1897 (PR https://github.com/kubernetes/cloud-provider-openstack/pull/1901) we added initial support for dual-stack k8s services. 

That implementation has a limitation: If two address families are specified in service's `spec.ipFamilies`, OCCM will create only one IPv4 or IPv6 load balancer - based on the first specified address family.

The aim of this task is to add full dual-stack support, which would create 2 load-balancers in case of two address families in the service's spec.

**Comment by ProbstDJakob** [comment]
Our proposal for the service annotations `v2` would be as follows:

```go
const (
	// [...] some other global constants

	ServiceAnnotationOCCMAPIVersion = "loadbalancer.openstack.org/occm-api-version"
)

const (
	// [...] the unchanged v1 annotations (except for their constant (var) names)
)

const (
	// Common options
	ServiceAnnotationV2LoadBalancerConnLimit            = "loadbalancer.openstack.org/connection-limit"
	ServiceAnnotationV2LoadBalancerClass                = "loadbalancer.openstack.org/class"
	ServiceAnnotationV2LoadBalancerProxyEnabled         = "loadbalancer.openstack.org/proxy-protocol"
	ServiceAnnotationV2LoadBalancerNetworkID            = "loadbalancer.openstack.org/network-id"
	ServiceAnnotationV2LoadBalancerTimeoutClientData    = "loadbalancer.openstack.org/timeout-client-data"
	ServiceAnnotationV2LoadBalancerTimeoutMemberConnect = "loadbalancer.openstack.org/timeout-member-connect"
	ServiceAnnotationV2LoadBalancerTimeoutMemberData    = "loadbalancer.openstack.org/timeout-member-data"
	ServiceAnnotationV2LoadBalancerTimeoutTCPInspect    = "loadbalancer.openstack.org/timeout-tcp-inspect"
	ServiceAnnotationV2LoadBalancerXForwardedFor        = "loadbalancer.openstack.org/x-forwarded-for"
	ServiceAnnotationV2LoadBalancerFlavorID             = "loadbalancer.openstack.org/flavor-id"
	ServiceAnnotationV2LoadBalancerAvailabilityZone     = "loadbalancer.openstack.org/availability-zone"
	// ServiceAnnotationV2LoadBalancerEnableHealthMonitor defines whether to create health monitor for the load balancer
	// pool, if not specified, use 'create-monitor' config. The health monitor can be created or deleted dynamically.
	ServiceAnnotationV2LoadBalancerEnableHealthMonitor         = "loadbalancer.openstack.org/enable-health-monitor"
	ServiceAnnotationV2LoadBalancerHealthMonitorDelay          = "loadbalancer.openstack.org/health-monitor-delay"
	ServiceAnnotationV2LoadBalancerHealthMonitorTimeout        = "loadbalancer.openstack.org/health-monitor-timeout"
	ServiceAnnotationV2LoadBalancerHealthMonitorMaxRetries     = "loadbalancer.openstack.org/health-monitor-max-retries"
	ServiceAnnotationV2LoadBalancerHealthMonitorMaxRetriesDown = "loadbalancer.openstack.org/health-monitor-max-retries-down"
	// revive:disable:var-naming
	ServiceAnnotationV2TlsContainerRef = "loadbalancer.openstack.org/default-tls-container-ref"
	// revive:enable:var-naming

	// IPv4 only options
	ServiceAnnotationV2LoadBalancerInternalIPv4           = "beta.ipv4.loadbalancer.openstack.org/internal"
	ServiceAnnotationV2LoadBalancerFloatingNetworkIDIPv4  = "ipv4.loadbalancer.openstack.org/floating-network-id"
	ServiceAnnotationV2LoadBalancerFloatingSubnetIPv4     = "ipv4.loadbalancer.openstack.org/floating-subnet"
	ServiceAnnotationV2LoadBalancerFloatingSubnetIDIPv4   = "ipv4.loadbalancer.openstack.org/floating-subnet-id"
	ServiceAnnotationV2LoadBalancerFloatingSubnetTagsIPv4 = "ipv4.loadbalancer.openstack.org/floating-subnet-tags"
	ServiceAnnotationV2LoadBalancerKeepFloatingIPIPv4     = "ipv4.loadbalancer.openstack.org/keep-floatingip"

	// IPv4 options
	ServiceAnnotationV2LoadBalancerPortIDIPv4               = "ipv4.loadbalancer.openstack.org/port-id"
	ServiceAnnotationV2LoadBalancerSubnetIDIPv4             = "ipv4.loadbalancer.openstack.org/subnet-id"
	ServiceAnnotationV2LoadBalancerMemberSubnetIDIPv4       = "ipv4.loadbalancer.openstack.org/member-subnet-id"
	ServiceAnnotationV2LoadBalancerLoadbalancerHostnameIPv4 = "ipv4.loadbalancer.openstack.org/hostname"
	ServiceAnnotationV2LoadBalancerAddressIPv4              = "ipv4.loadbalancer.openstack.org/load-balancer-address"
	ServiceAnnotationV2LoadBalancerIDIPv4                   = "ipv4.loadbalancer.openstack.org/load-balancer-id"

	// IPv6 options
	ServiceAnnotationV2LoadBalancerPortIDIPv6               = "ipv6.loadbalancer.openstack.org/port-id"
	ServiceAnnotationV2LoadBalancerSubnetIDIPv6             = "ipv6.loadbalancer.openstack.org/subnet-id"
	ServiceAnnotationV2LoadBalancerMemberSubnetIDIPv6       = "ipv6.loadbalancer.openstack.org/member-subnet-id"
	ServiceAnnotationV2LoadBalancerLoadbalancerHostnameIPv6 = "ipv6.loadbalancer.openstack.org/hostname"
	ServiceAnnotationV2LoadBalancerAddressIPv6              = "ipv6.loadbalancer.openstack.org/load-balancer-address"
	ServiceAnnotationV2LoadBalancerIDIPv6                   = "ipv6.loadbalancer.openstack.org/load-balancer-id"
)
```

As one may notice to be consistent with the other annotations I renamed the `service.beta.kubernetes.io/openstack-internal-load-balancer` `v1` annotation to `beta.ipv4.loadbalancer.openstack.org/internal`. I am not sure if this is a good change since it is referenced in the [kubernetes docs](https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer) (within the OpenStack tab), but this way it is obvious it only applies to IPv4 (more or less).

The `internal` option itself is a bit problematic since it should make the load balancer only accessible within the OpenStack project, but with the support of IPv6 this is not really the case any more. When setting the `internal` option to `true` no floating ip will be created and the load balancer can not be shared between multiple services. The current IPv6 implementation does in order to prevent the creation of a floating ip set the option to `true` which has the side effect that the load balancer can not be shared. This I would fix, but what I can not _fix_ is that IPv6 can never be _internal_ unless the network will not be routed to the internet and that is not in the scope/responsibility of OCCM. Thus this option should be reworked and yes this might be a separate issue but in case this versioning will be accepted it would be good if `v2` does not have this issue, otherwise a `v3` would probably be needed soon after.

My suggestion would be to use instead of an `internal` annotation an annotation like `create-floating-ip` and in the global config the `internal` option should also be dropped and replaced by `allow-creating-floating-ip`, `allow-ipv4`, and `allow-ipv6`. But as I said, such a discussion should probably take place in another issue.

**Comment by ProbstDJakob** [comment]
@dulek @jichenjc @kayrus @zetaab Can anyone please look at this issue? No rush, I only think that you did not get noticed about the comments I made, since it is a closed issue.

**Comment by kayrus** [comment]
I'll take a look later. It's a big task, and it looks like it cannot be shipped to 1.29 release. First of all we need to fix some lbaas related bugs.

**Comment by ProbstDJakob** [comment]
I came to the same conclusion the more I looked into the code and what has too be done/what decisions have to be made.

**Comment by dulek** [comment]
Yep, this is still valid. I've looked through your comments @ProbstDJakob, very good stuff.

So you're looking at creating 2 separate LBs for each dual-stack LB Service. This is something we've looked at too, but not in so detailed manner.

One thing to consider is that I think we can make an assumption that order of the LB IDs and port IDs on the annotation will match order of what's on the Service's `ipFamilies`, because it's only mutable in a way we could support:

> This field is conditionally mutable: it allows for adding or removing a secondary IP family, but it does not allow changing the primary IP family of the Service.

In case of the confusion of old and new parameters, I think this piece about K8s API might apply to us: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#making-a-singular-field-plural. TLDR: You need clients to specify both old and new field correctly in order for this to work in a consistent way.

**Comment by ProbstDJakob** [comment]
Sorry for the late response. The topic _Making a singular field plural_ is more or less the same as with what we came up with with the exception, correct me if I am wrong, that we do not see a _history_. If a change to a manifest happens, we only get the latest manifest version but not what has changed or the version before (if it is an update). If that is the case, it would make some parts of the k8s doc hard to realize.

Until now we did not further investigate the issue or wrote some code, but we are still interested in getting this done, thus are willing to contribute as soon as some decisions have been made.

**Comment by nashford77** [comment]
How can we progress this issue? Is there any way i can help as i have dual stack running across my network and cloud?

**Comment by ProbstDJakob** [comment]
That would be great to test. We currently do not have a dual stack cluster. If I have some spare time I would rewrite the CI/CD to deploy our testing cluster with dual stack, but I do not know when I have time since there is little benefit now.

I think the first/next step is to decide on how to implement this, but that is probably nothing we can do.

**Comment by dulek** [comment]
> Sorry for the late response. The topic _Making a singular field plural_ is more or less the same as with what we came up with with the exception, correct me if I am wrong, that we do not see a _history_. If a change to a manifest happens, we only get the latest manifest version but not what has changed or the version before (if it is an update). If that is the case, it would make some parts of the k8s doc hard to realize.

This thing is about CRD versions, so I guess previous version is the history you have access to.

> Until now we did not further investigate the issue or wrote some code, but we are still interested in getting this done, thus are willing to contribute as soon as some decisions have been made.

Doesn't seem like anyone else wants to chime in, so I'll play a dictator here. For the internal option - let's keep it but document it is IPv4-only. If it's set for an IPv6 or dual stack, we'll emit a warning event on the Service.

As for annotation versioning, I think the canonical way to do this is to add both versions of the informative annotations, but for the functional ones - new versions always takes precedence. I.e. if v1 and v2 annotations are set, only v2 are taken into account when creating the LB. That way if someone is using a toolchain expecting v1, then they are okay. If you want new features, then you need your toolchain fully upgraded.

**Comment by ProbstDJakob** [comment]
Sorry for the late response. I am currently a bit overwhelmed with work and have to write a master thesis. Thus I am currently not able to pursue this issue (or more precisely write code/answer in time) until early next year. If someone else is willing to take over, I am happy to assist (as time permits). Also, our testing cluster now has support for dual stack and can freely be re-deployed at any time (fully automatically) which then can be used to test changes to the OCCM.
