### ISSUE TITLE
cinder-CSI: support fsGroup in CSI 

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#2075]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

check https://kubernetes-csi.github.io/docs/support-fsgroup.html
looks like CSI can support this fsGroup feature, not sure whether openstack user need this or not..

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by mogindi** [comment]
Hi,

just want to clarify, cinder currently does **not** support fsGroups, right? I've been trying to troubleshoot this all day

**Comment by RoSk0** [comment]
I was having OpenStack provided volumes mounted as `root:root` and thinking it's me who missing something apart from using the `fsGroup` specified in a Pod's `securityContext` until someone pointed me at https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/csi/cinder/nodeserver.go saying it's not implemented...

Ashame that this feature , that personally feels like really important one, is not implemented. I wish I would have any Golang or OpenStack experience to dive into implementation...

**Comment by amgonzalezf** [comment]
I've been also trying to make a volume to be mounted as other than 'root:root' and it didn't work so far. As @RoSk0 , I tried with 'fsGroup' but that didn't make any difference. In my case, this problem happens when I create a PVC that consumes a storageclass designed for multiattach (ReadWriteMany PVCs). If the storageclass is the one that I use for ReadWriteOnce PVCs, the group that owns the volume can be different than 'root:root' (apparently, it's set using the fsGroup, so if the fsGroup is '1001', the volume will be mounted as 'root:1001').

**Comment by euven** [comment]
I've been looking into this a bit and it looks like you can indeed use `fsGroup` successfully. 

What caught us out, is having a `ReadWriteMany` accessModes` set on the PVC, instead of obviously having to use `ReadWriteOnce`, i.e:

```
spec:
  storageClassName: b1.standard
  accessModes:
    - ReadWriteOnce
```

Hope this helps someone!
