### ISSUE TITLE
Gate failure: install devstack issue

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#2083]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

install devstack failed , block all CI
e.g https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/cloud-provider-openstack/2077/openstack-cloud-controller-manager-e2e-test/1618320987739131904/build-log.txt

complain about 
```
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '0.23ubuntu1' (package: distro-info)
```

looks like https://bugs.launchpad.net/ubuntu/+source/distro-info/+bug/2003583

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by Joffref** [comment]
Hello @jichenjc, 

This problem seems mostly related to [this issue from setuptools](https://github.com/pypa/setuptools/issues/3772) and as I understood, this will never be fixed. 

Knowing that the Devstack requirements are pinned, this issue seems to mainly came from the workflow. By reading output from some of them, we can see that setuptools isn't downloaded by pip as the version 66.0 seems to be already available in the container.

I think [these line from ansible](https://github.com/kubernetes/cloud-provider-openstack/blob/44c9be84ceadb91812e9dd89cc4ecb1b507eea8e/tests/playbooks/roles/install-devstack/tasks/main.yml#L47) should be removed, to let the Devstack download the right version of setuptools.

**Comment by jichenjc** [comment]
Thanks for the info and I actually tried with https://github.com/kubernetes/cloud-provider-openstack/pull/2084
as indicated in the PR, seems I can pass the original issue then still not able to create devstack
not sure it's the change's side effect or trigger other potential issue..
