### ISSUE TITLE
[oocm] generates an excessive number of os-interface api requests

### ISSUE THREAD

**Issue by databus23** [kubernetes/cloud-provider-openstack#2089]
> /kind bug

**What happened**:
We recently noticed that our nova api is handling a constant excessive amount of os-interface (list) calls.
This in turn puts a lot of strain on our neutron API as os-interface calls gets forwarded by nova to neutron as get_ports API calls.

It turns out this constant high load is almost exclusively caused by various occm instances running in our OpenStack installation.

Looking at the occm code there is [five different places](https://github.com/kubernetes/cloud-provider-openstack/search?q=getAttachedInterfacesByID) where `getAttachedInterfacesByID` is called: for routes, load balancers and instances.

It seems the use of `getAttachedInterfacesByID` for the routes controller is the most costly inducing a lot of os_interfaces calls at a high frequency:
[For every instance in the project `os_interfaces` is called at the rate of the routes controller](https://github.com/kubernetes/cloud-provider-openstack/blob/98b9a89ceb0379e794e6ada1976e32c9da80af31/pkg/openstack/routes.go#L65-L66) which is 10 seconds by default. This is regardless of the cluster size. We have a cluster with 4 nodes in a project with 1000 instances and in this case occm is generating about 1000 os_interface list calls every 10 seconds.

I would like to start discussing options how the current behaviour  could be improved, so that the base load of generated API requests by occm is reduced for bigger setups.

My first suggestion would be:
Instead of discovering node ip addresses in three different control loops independently (load balancers, routes, instances) they should only be fetched from the instance controller that reconciles the node status. All other control loops should only read ip addresses from the node status (k8s API).

**What you expected to happen**:
That occm generates less constant load on the OpenStack APIs

**How to reproduce it**:
Create a cluster in a project with a lots of vms and configure oocm to set cloud-routes.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version: 1.25

**Comment by jichenjc** [comment]
I like the idea and maybe we need think about where's the info stored
seems no good place to store in node.Status https://github.com/kubernetes/api/blob/v0.26.1/core/v1/types.go#L5183

so maybe store some global cache and only update the cache in the instance reconcile and others get the cache directly
if no cache no hit, fall back to API call

getAttachedInterfacesByID actually have a metrics about the API been called ,that might also be measured later on after enhancement

**Comment by databus23** [comment]
> seems no good place to store in node.Status

I was thinking about using [status.addresses](https://github.com/kubernetes/api/blob/v0.26.1/core/v1/types.go#L5212) which is already updated by the [cloud node controller periodically](https://github.com/kubernetes/cloud-provider/blob/d6f014b3db04edde27d12b1bbc427c4114e70543/controllers/node/node_controller.go#L176-L182).

It seems by default the update frequency is [5 minutes](https://github.com/kubernetes/cloud-provider/blob/2b22435df4b2d512b4ec0eeddba375fcdcc1e642/config/v1alpha1/defaults.go#L37) so this might introduce a significant delay until changes in node addresses are reflected. To alleviate the node status update frequency could be exposed as a command line flag. Its not at the moment but its already a config option.

**Comment by zetaab** [comment]
we should run occm in leader election turned on if we have multiple of them at the same time. IMO it is enough if we cache that information in current leader memory? kOps for instance uses similar method https://github.com/kubernetes/kops/blob/master/pkg/nodeidentity/openstack/identify.go#L111-L158 using "k8s.io/client-go/tools/cache"

**Comment by jichenjc** [comment]
getAttachedInterfacesByID return []attachinterfaces.Interface , so it's a set of openstack concepts 
https://github.com/kubernetes/api/blob/v0.26.1/core/v1/types.go#L5387, it's a set of NodeAddress type so we can't use it to store

but seems mostly getAttachedInterfacesByID used are to get interfaces then use nodeAddresses to get Node adresss
so if we can cache the node address somewhere then use it mostly by using the way zetaab mentioned above

**Comment by databus23** [comment]
I'm not sure I understand the way @zetaab suggested. We are running occm as a single instance per cluster and see the excessive amounts of api calls. Our problem is not that when running with multiple replicas that each replica is making the api requests.
We have > 500 clusters in our openstack installation and that makes > 500 oocm instances hammering the openstack api with list interface api calls.

**Comment by kayrus** [comment]
I don't think it's a good idea to cache non-related information in OCCM cache. I made a couple of improvements in #2090 which don't use caching at all in:
* I completely removed `foreachServer`.
* I'm using a simple servers list, which returns only a server name.

Both drastically improves the OCCM `ListRoutes` performance keeping the original _resolve_ logic.

**Comment by kayrus** [comment]
I observed another nasty bug in routes logic. Routes controller has max concurrent routes creations set to 200, which means, if you have 200 nodes, all 200 nodes will simultaneously create routes on the router. Due to OpenStack specifics you cannot create a route, you can only update routes table on one specific router. This behavior would lead to a number of retries of the router update until the desired state is achieved.

https://github.com/kubernetes/cloud-provider/blob/301838b0e28cc71bfff456228d5ed772a2976f29/controllers/route/route_controller.go#L48-L52

https://github.com/kubernetes/cloud-provider/blob/301838b0e28cc71bfff456228d5ed772a2976f29/controllers/route/route_controller.go#L187-L220

Therefore I added a lock to CreateRoute and Delete route methods: https://github.com/kubernetes/cloud-provider-openstack/pull/2090/commits/e8feac365298feb7c578eb230d40eb42e6e250ca

**Comment by kayrus** [comment]
I updated the PR and completely removed nova API calls from the routes reconciliation logic. Instead of nova API the new logic now uses k8s node informer, which already is managed by OCCM node discovery. The amount of API calls for routes reconciliation from scratch (no routes) is now decreased from hundreds per k8s node to 3 per k8s node.

Unfortunately k8s cloud controller interface supports only a single route update:
https://github.com/kubernetes/cloud-provider/blob/5494e3eb2229ce2cddec4e0fb2cea7272303db8e/cloud.go#L236

I can try to implement batch routes update on the ListRoutes call, or create a worker with a queue, which will update routes from an internal queue every N seconds.
