### ISSUE TITLE
[occm] Internal Service might be exposed when LB is shared

### ISSUE THREAD

**Issue by dulek** [kubernetes/cloud-provider-openstack#2174]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When you create a Service with `service.beta.kubernetes.io/openstack-internal-load-balancer: "true"` annotation and then create another regular non-internal Service that's supposed to share the LB with the previous one, CPO will allow that and will attach the FIP to the load balancer. This will expose the both Services outside, including the one that supposed to only be internal. While a bit obscure, it's a potential security risk that a confused user might create without knowing.

**What you expected to happen**:
Either sharing internal LB with an external Service is blocked or there's a way to only expose one listener from a share LB. I don't think the latter is possible.

**How to reproduce it**:
Explained above.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:  master
- OpenStack version: Doesn't matter
- Others:

**Comment by mdbooth** [comment]
Trying to wrap my head round this. Do you have example yaml for both services?

**Comment by kayrus** [comment]
@mdbooth the bug relates to a shared loadbalancer: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/openstack-cloud-controller-manager/expose-applications-using-loadbalancer-type-service.md#sharing-load-balancer-with-multiple-services
Indeed we should not mix up the private and public loadbalancers as a shared entity, since the FIP is assigned to a loadbalancer, not to a listener. This also should be mentioned in docs.

**Comment by jichenjc** [comment]
good catch, I Think `Either sharing internal LB with an external Service is blocked ` is the best option
@dulek guess you will submit a PR ,correct? we can update Doc to indicate this restriction as well if needed
