### ISSUE TITLE
Possibly redundant calls to the Nova Metadata service

### ISSUE THREAD

**Issue by pierreprinetti** [kubernetes/cloud-provider-openstack#2224]
As discussed in #2217, calls to the Nova Metadata service could probably be reduced when the only goal is to retrieve the instance's ID.

Since the ID is never going to change, it could be fetched once and persisted in memory.

If there is consensus on a need for action on this one, I'd be glad to take it.

CC @zetaab @mdbooth @jichenjc

**Comment by jichenjc** [comment]
we try to read `const instanceIDFile = "/var/lib/cloud/data/instance-id` if metadata service got some problem and we think local might change
https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/openstack/instances.go#L514

but seems we should honor local value then try metadata and store the metadata result as cache (as proposed above) ..?

**Comment by mdbooth** [comment]
I think we can close this because we're already caching it: https://github.com/openshift/cloud-provider-openstack/blob/0eacab836b290551a6e058f7c6adb55747f1b591/pkg/util/metadata/metadata.go#L259-L260

So whether we're fetching from config drive or metadata, both [GetInstanceID](https://github.com/openshift/cloud-provider-openstack/blob/0eacab836b290551a6e058f7c6adb55747f1b591/pkg/util/metadata/metadata.go#L289-L296) and [GetAvailabilityZone](https://github.com/openshift/cloud-provider-openstack/blob/0eacab836b290551a6e058f7c6adb55747f1b591/pkg/util/metadata/metadata.go#L298-L305) will fetch the full metadata struct from the cache and therefore only ever hit the metadata service at most once. As both of these are static[^1] this seems fine.

[^1]: InstanceID can only be static. AZ can technically change, but only in a forced live migration by an OpenStack admin with an explicit destination host which violates the server's AZ constraint. This isn't a recommended way to do live migrations.

[GetDevicePath](https://github.com/openshift/cloud-provider-openstack/blob/0eacab836b290551a6e058f7c6adb55747f1b591/pkg/util/metadata/metadata.go#L210-L255) doesn't use the cache, which is also correct. Fetching this every time is unavoidable.

There is a subtle problem with this code, though: setting the cache itself is racy. The cache is set in code which is called by the gRPC server, which is multi-threaded. 2 threads can obviously race to set the cache initially, but while that's a bit inefficient it's not actually a problem as they should both fetch and therefore cache the same data. However, setting a pointer in Go isn't an atomic operation, which means that [reading the cache pointer](https://github.com/openshift/cloud-provider-openstack/blob/0eacab836b290551a6e058f7c6adb55747f1b591/pkg/util/metadata/metadata.go#L259-L260) and [setting the cache pointer](https://github.com/openshift/cloud-provider-openstack/blob/0eacab836b290551a6e058f7c6adb55747f1b591/pkg/util/metadata/metadata.go#L283-L284) currently have undefined behaviour. This is probably the least problematic category of race conditions, but if we want to be 100% safe we should probably fix it with either a mutex or an atomic load and store.

@pierreprinetti close this and create a new issue for the race?
