### ISSUE TITLE
cinder-csi: consider using ClusterFirstWithHostNet DNSPolicy

### ISSUE THREAD

**Issue by rptaylor** [kubernetes/cloud-provider-openstack#2574]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
Cinder CSI is using ClusterFirst DNSPolicy, but also appears to use hostNetwork.
Following up from https://github.com/kubernetes/cloud-provider-openstack/issues/1387#issuecomment-2052269578 , it seems like using ClusterFirstWithHostNet could be better but it's not entirely clear to me.  FYI @jichenjc 

**Anything else we need to know?**:
See https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy

**Environment**:
- openstack-cloud-controller-manager(or other related binary) version:
- OpenStack version:
- Others:

**Comment by dulek** [comment]
Seems like the chart has this configurable [1] and the default is in fact `ClusterFirstWithHostNet` [2]. This got fixed in #2483. What am I missing?

[1] https://github.com/kubernetes/cloud-provider-openstack/blob/8a156e543ca44924a5f26aaf001fb86bcbd100f9/charts/cinder-csi-plugin/templates/nodeplugin-daemonset.yaml#L27
[2] https://github.com/kubernetes/cloud-provider-openstack/blob/d64cd51353b0620dacf2aea868e0b282bb92fded/charts/cinder-csi-plugin/values.yaml#L72

**Comment by rptaylor** [comment]
Oh, good to see it was already discussed. I guess the recent comment https://github.com/kubernetes/cloud-provider-openstack/issues/1387#issuecomment-2052269578  mislead us then.
