### ISSUE TITLE
rename client-keystone-auth to kubectl-keystone-auth

### ISSUE THREAD

**Issue by attardi** [kubernetes/cloud-provider-openstack#387]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
According to Keystone conventions (https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/), plugins should be named with prefix kubectl-, therefore client-keystone-auth should be renamed as kubectl-keystone-auth.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dims** [comment]
The convention is true for "simple" plugins that do not need much configuration i believe. 

Also, Does the instructions below fail?
https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-client-keystone-auth.md#configuration

cc @openstacker @attardi @Fedosin

**Comment by Fedosin** [comment]
Hi! client-keystone-auth is not a kubectl plugin, it is a credential plugin. You can read more about them here: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
First of all, these plugins are used not just by kubectl, but also by kubelet. They don't add any new options to kubectl, they just help to implicitly authenticate the user and get a token that then will be attached to his request to the API service.
That's why I think that this renaming is unnecessary.
