### ISSUE TITLE
openstack-ingress-controller failed 

### ISSUE THREAD

**Issue by hemantsonawane95** [kubernetes/cloud-provider-openstack#446]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
Failed to create openstack resources for ingress default/test-octavia-ingress: error because no members in pool
**What you expected to happen**:
openstack-ingress-controller should work 
**How to reproduce it (as minimally and precisely as possible)**:

can be fixed by adding worker node to the cluster.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.4.0-134-generic
- Install tools: kubeadm 
- Others: Cloud-provider= Openstack

**Comment by jichenjc** [comment]
@hemantsonawane95 This logic is added to avoid this bug:
https://github.com/kubernetes/cloud-provider-openstack/issues/378

because openstack does not support no member in lb , calling octavia API without member will lead to 500 internal error, so we added this check

can you help to check whether you have node in your definition (not all-in-one master only) ,if no node defined, can you add one and try again?

**Comment by jichenjc** [comment]
ok, let's close this per above comments...

**Comment by lingxiankong** [comment]
@hemantsonawane95 If you really want the ingress controller works in a single node cluster, you could remove the taint on the master node by running `kubectl taint nodes <YOUR-MASTER-NODE-NAME> node-role.kubernetes.io/master-`

**Comment by jichenjc** [comment]
I tried before and it doesn't work .... maybe I did something wrong before..

**Comment by chaosaffe** [comment]
@lingxiankong Is there a reason we explicitly exclude an in-cluster `master` from receiving ingress traffic? In practice a master can handle ingress of traffic just as well as any other node within the cluster, and would simplify a lot of the Octavia handling.

**Comment by lingxiankong** [comment]
@chaosaffe It only makes sense for the master to be a load balancer member, if the master is schedulable, i.e. you need to run `kubectl taint nodes <YOUR-MASTER-NODE-NAME> node-role.kubernetes.io/master-`

**Comment by jichenjc** [comment]
@lingxiankong so the LB (ingress) does not make sense to master as LB only used for workload pod (not infra pod), that means master node which won't have worker pod scheduled does not need to honor the LB settings.. my understanding correct?

**Comment by lingxiankong** [comment]
@jichenjc yep, correct.

**Comment by elgamal2020** [comment]
Hello,
I would need your help
I have the same problem in all in one cluster 

ubuntu@external2:/etc/kubernetes/octavia-ingress-controller$ kubectl logs octavia-ingress-controller-0 -n kube-system
W0924 03:08:40.373027       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-09-24T03:08:40Z" level=info msg="Using config file" file=/etc/config/octavia-ingress-controller-config.yaml
I0924 03:08:41.084436       1 event.go:282] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"test-octavia-ingress", UID:"5dc2f735-019f-46bb-aaa1-6cae487042f7", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"1975558", FieldPath:""}): type: 'Normal' reason: 'Creating' Ingress default/test-octavia-ingress
time="2020-09-24T03:08:41Z" level=info msg="ingress controller synced and ready"
time="2020-09-24T03:08:41Z" level=info msg="ingress created, will create openstack resources" ingress=default/test-octavia-ingress
time="2020-09-24T03:08:41Z" level=info msg="ensuring security group" ingress=default/test-octavia-ingress
time="2020-09-24T03:08:41Z" level=info msg="ensured security group" ingress=default/test-octavia-ingress sgID=7ad2c1a8-d5ba-44a9-915a-8d97abf38559
time="2020-09-24T03:08:45Z" level=info msg="pool created" lb=0250692a-e931-413c-82bd-c64ca56d2532 listenerID= pooID=36432dca-448e-4575-a86f-7e657cbf4cf0 poolName=756071a3be4dcd3b7a89eadda960584fc2e249ec770b6864d5ba49c7bb292573
ubuntu@external2:/etc/kubernetes/octavia-ingress-controller$ kubectl logs octavia-ingress-controller-0 -n kube-system
W0924 03:08:40.373027       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2020-09-24T03:08:40Z" level=info msg="Using config file" file=/etc/config/octavia-ingress-controller-config.yaml
I0924 03:08:41.084436       1 event.go:282] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"test-octavia-ingress", UID:"5dc2f735-019f-46bb-aaa1-6cae487042f7", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"1975558", FieldPath:""}): type: 'Normal' reason: 'Creating' Ingress default/test-octavia-ingress
time="2020-09-24T03:08:41Z" level=info msg="ingress controller synced and ready"
time="2020-09-24T03:08:41Z" level=info msg="ingress created, will create openstack resources" ingress=default/test-octavia-ingress
time="2020-09-24T03:08:41Z" level=info msg="ensuring security group" ingress=default/test-octavia-ingress
time="2020-09-24T03:08:41Z" level=info msg="ensured security group" ingress=default/test-octavia-ingress sgID=7ad2c1a8-d5ba-44a9-915a-8d97abf38559
time="2020-09-24T03:08:45Z" level=info msg="pool created" lb=0250692a-e931-413c-82bd-c64ca56d2532 listenerID= pooID=36432dca-448e-4575-a86f-7e657cbf4cf0 poolName=756071a3be4dcd3b7a89eadda960584fc2e249ec770b6864d5ba49c7bb292573
E0924 03:08:48.726880       1 controller.go:485] failed to create openstack resources for ingress default/test-octavia-ingress: error because no members in pool: 36432dca-448e-4575-a86f-7e657cbf4cf0
I0924 03:08:48.727580       1 event.go:282] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"test-octavia-ingress", UID:"5dc2f735-019f-46bb-aaa1-6cae487042f7", APIVersion:"networking.k8s.io/v1beta1", ResourceVersion:"1975558", FieldPath:""}): type: 'Warning' reason: 'Failed' Failed to create openstack resources for ingress default/test-octavia-ingress: error because no members in pool: 36432dca-448e-4575-a86f-7e657cbf4cf0


and it is already untained 

ubuntu@external2:/etc/kubernetes/octavia-ingress-controller$ kubectl taint nodes --all node-role.kubernetes.io/master-
error: taint "node-role.kubernetes.io/master" not found
ubuntu@external2:/etc/kubernetes/octavia-ingress-controller$ kubectl describe node external2
Name:               external2
Roles:              master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=852e8aaf-c67a-4033-a129-01e74063c0fe
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=RegionOne
                    failure-domain.beta.kubernetes.io/zone=nova
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=external2
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/master=
                    node.kubernetes.io/instance-type=852e8aaf-c67a-4033-a129-01e74063c0fe
                    topology.cinder.csi.openstack.org/zone=nova
                    topology.kubernetes.io/region=RegionOne
                    topology.kubernetes.io/zone=nova
Annotations:        alpha.kubernetes.io/provided-node-ip: 10.20.20.124
                    csi.volume.kubernetes.io/nodeid: {"cinder.csi.openstack.org":"f82cb81b-8dac-4679-9c30-9ec36ed11886"}
                    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 16 Sep 2020 02:53:33 +0000
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  external2
  AcquireTime:     <unset>
  RenewTime:       Thu, 24 Sep 2020 03:10:28 +0000
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Wed, 16 Sep 2020 02:55:00 +0000   Wed, 16 Sep 2020 02:55:00 +0000   CalicoIsUp                   Calico is running on this node
  MemoryPressure       False   Thu, 24 Sep 2020 03:10:22 +0000   Wed, 16 Sep 2020 02:53:28 +0000   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Thu, 24 Sep 2020 03:10:22 +0000   Wed, 16 Sep 2020 02:53:28 +0000   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Thu, 24 Sep 2020 03:10:22 +0000   Wed, 16 Sep 2020 02:53:28 +0000   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Thu, 24 Sep 2020 03:10:22 +0000   Wed, 16 Sep 2020 02:54:49 +0000   KubeletReady                 kubelet is posting ready status. AppArmor enabled
Addresses:
  InternalIP:  10.20.20.124
  Hostname:    external2
Capacity:
  cpu:                4
  ephemeral-storage:  20145724Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             8152784Ki
  pods:               110
Allocatable:
  cpu:                3800m
  ephemeral-storage:  18566299208
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             7550384Ki
  pods:               110
System Info:
  Machine ID:                 f82cb81b8dac46799c309ec36ed11886
  System UUID:                f82cb81b-8dac-4679-9c30-9ec36ed11886
  Boot ID:                    cd3a0d6c-3cf9-4b57-b28d-3967ccffceb9
  Kernel Version:             5.4.0-42-generic
  OS Image:                   Ubuntu 20.04.1 LTS
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://19.3.12
  Kubelet Version:            v1.18.8
  Kube-Proxy Version:         v1.18.8
PodCIDR:                      10.235.64.0/24
PodCIDRs:                     10.235.64.0/24
ProviderID:                   openstack:///f82cb81b-8dac-4679-9c30-9ec36ed11886
Non-terminated Pods:          (16 in total)
  Namespace                   Name                                            CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----                                            ------------  ----------  ---------------  -------------  ---
  default                     webserver-58fcfb75fb-g7ld2                      0 (0%)        0 (0%)      0 (0%)           0 (0%)         24h
  kube-system                 calico-kube-controllers-7958687d48-lwrxm        30m (0%)      100m (2%)   64M (0%)         256M (3%)      8d
  kube-system                 calico-node-zgk4d                               150m (3%)     300m (7%)   64M (0%)         500M (6%)      8d
  kube-system                 coredns-dff8fc7d-pmw4b                          100m (2%)     0 (0%)      70Mi (0%)        170Mi (2%)     8d
  kube-system                 csi-cinder-controllerplugin-86dc54996d-dzpr5    0 (0%)        0 (0%)      0 (0%)           0 (0%)         8d
  kube-system                 csi-cinder-nodeplugin-7snvn                     0 (0%)        0 (0%)      0 (0%)           0 (0%)         8d
  kube-system                 dns-autoscaler-66498f5c5f-2hr7p                 20m (0%)      0 (0%)      10Mi (0%)        0 (0%)         8d
  kube-system                 kube-apiserver-external2                        250m (6%)     0 (0%)      0 (0%)           0 (0%)         8d
  kube-system                 kube-controller-manager-external2               200m (5%)     0 (0%)      0 (0%)           0 (0%)         8d
  kube-system                 kube-multus-ds-amd64-mnm72                      100m (2%)     100m (2%)   90Mi (1%)        90Mi (1%)      8d
  kube-system                 kube-proxy-zdrvx                                0 (0%)        0 (0%)      0 (0%)           0 (0%)         8d
  kube-system                 kube-scheduler-external2                        100m (2%)     0 (0%)      0 (0%)           0 (0%)         8d
  kube-system                 nodelocaldns-2c4b4                              100m (2%)     0 (0%)      70Mi (0%)        170Mi (2%)     8d
  kube-system                 octavia-ingress-controller-0                    0 (0%)        0 (0%)      0 (0%)           0 (0%)         112s
  kube-system                 openstack-cloud-controller-manager-n25hl        200m (5%)     0 (0%)      0 (0%)           0 (0%)         8d
  kube-system                 snapshot-controller-0                           0 (0%)        0 (0%)      0 (0%)           0 (0%)         8d
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests        Limits
  --------           --------        ------
  cpu                1250m (32%)     500m (13%)
  memory             379658240 (4%)  1206887680 (15%)
  ephemeral-storage  0 (0%)          0 (0%)
  hugepages-1Gi      0 (0%)          0 (0%)
  hugepages-2Mi      0 (0%)          0 (0%)
Events:              <none>
