### ISSUE TITLE
octavia ingress controller fails to create members for pool

### ISSUE THREAD

**Issue by DJAyth** [kubernetes/cloud-provider-openstack#623]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Setup via the documentation link the octavia-ingress-controller as I am using an openstack provider, and stumbled upon it earlier today. Was able to deploy the ingress and the pods for the ingress controller start fine.

However, when I create a service and attempt to use the ingress I am getting a failure in the process. It successfully created the loadbalancer, listener and pool for the LB, but it seems to fail upon the creation of the members.

Openstack version is currently Pike.

**What you expected to happen**:

Expected a successful creation of a loadbalancer.

**How to reproduce it (as minimally and precisely as possible)**:

Create ingress controller
Create service specifying the ingress as octavia
Failure

**Anything else we need to know?**:
Logs from the ingress controller pod are as follows:

time="2019-05-27T18:47:43Z" level=info msg="pool created" lb=604db636-13b3-4a57-b929-a8ea06c64c8f listenerID= pooID=b9e7789b-bd8e-4462-94e0-9efa5735009c poolName=1ba66bad913ad18578700de956f94b9fc99d41a30774794eddb41751bf395807
E0527 18:47:47.304409 1 controller.go:449] failed to create openstack resources for ingress default/test-octavia-ingress: error batch updating members for pool b9e7789b-bd8e-4462-94e0-9efa5735009c: Bad request with: [PUT https://myprovider.cloud:9876/v2.0/lbaas/pools/b9e7789b-bd8e-4462-94e0-9efa5735009c/members], error message: {"debuginfo": null, "faultcode": "Client", "faultstring": "Unknown attribute for argument member_: members"}
I0527 18:47:47.304725 1 event.go:209] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"test-octavia-ingress", UID:"cb4f748d-80a8-11e9-b6f0-fa163e957315", APIVersion:"extensions/v1beta1", ResourceVersion:"11209", FieldPath:""}): type: 'Warning' reason: 'Failed' Failed to create openstack resources for ingress default/test-octavia-ingress: error batch updating members for pool b9e7789b-bd8e-4462-94e0-9efa5735009c: Bad request with: [PUT https://myprovider.cloud:9876/v2.0/lbaas/pools/b9e7789b-bd8e-4462-94e0-9efa5735009c/members], error message: {"debuginfo": null, "faultcode": "Client", "faultstring": "Unknown attribute for argument member_: members"}

My credentials are fine as it does create some resources, but in the process based on the logs it fails to create the members in the pool.

**Environment**:
- octavia-ingress-controller version: v1.14.0
- OS (e.g. from /etc/os-release): ubuntu 18.04
- Kernel (e.g. `uname -a`): 4.15.0-50-generic

**Comment by mikejoh** [comment]
I tried to have a look at this but i couldn't find the exact reason for why this failing for you, this is what i've found by jumping around the source code and the documentation:

The first error message is from `controller.go` and comes from this if-statement:
https://github.com/kubernetes/cloud-provider-openstack/blob/34caa4ccbbde4e87d4bdc43512bb1af76f7bafa5/pkg/ingress/controller/controller.go#L448-L453

That `ensureIngress` method call is performing some operations to set everything up in regards to the Octavia loadbalancer and related objects. In the `ensureIngress`method there are three calls to the `EnsurePoolMembers` method that i suspect are part of your problem and i'm guessing it could be this one:

https://github.com/kubernetes/cloud-provider-openstack/blob/34caa4ccbbde4e87d4bdc43512bb1af76f7bafa5/pkg/ingress/controller/controller.go#L582

Anyways the `EnsurePoolMembers` method call can end up in the following error:

https://github.com/kubernetes/cloud-provider-openstack/blob/34caa4ccbbde4e87d4bdc43512bb1af76f7bafa5/pkg/ingress/controller/openstack/octavia.go#L477-L479

Which is what we can see in you error messages. So that `BatchUpdateMembers` seems to fail for some reason, digging a bit further we end up in the `gophercloud` Go-lang packages for interacting with different OpenStack API's. Here's the `BatchUpdateMembers` method in the `pools` package:

https://github.com/gophercloud/gophercloud/blob/3ad89c4ea008e0e0b729720040b0be25a35d4615/openstack/loadbalancer/v2/pools/requests.go#L355-L371

That code (and more) where added around nine months ago through this PR: https://github.com/gophercloud/gophercloud/pull/1229

I'm still kind of novice to both OpenStack and Go-lang so i can't spot any obvious problems in the code.
With that said i suspect that being on Pike and using the Octavia Ingress controller might be problematic in itself. But i don't have any scientific evidence for that! Here's the [API ref documentation](https://developer.openstack.org/api-ref/load-balancer/v2/?expanded=batch-update-members-detail) describing the batch update operation added in Octavia. In the beginning of that document they mention that Octavia is fully backwards compatible with Neutron LBaaS API which in turn nowadays isn't maintained any longer as i understand. To find the Neutron LBaaS source code for Pike browse to this [repository](https://github.com/openstack/neutron-lbaas/), change to the `stable/pike` branch to see the source code.

So to wrap up, the last part of the error messages you get there's this line embedded in a response as it looks like:

`{"debuginfo": null, "faultcode": "Client", "faultstring": "Unknown attribute for argument member_: members"}`

The `member_: members` part might be interesting to look at more closely, those HTTP 400 responses can obviously be due to a lot of different reasons (taken from the Octavia API docs):

- Bad request (!)
- Malformed request URI or body requested
- The request could not be understood
- Invalid values entered
- Bulk operations disallowed
- Validation failed
- Method not allowed for request body (such as trying to update attributes that can be specified at create-time only)

Hopefully someone else in here could shed some light on this for you!

**Comment by lingxiankong** [comment]
Hi, what Octavia version are you using? Did you check the octavia worker log?

**Comment by DJAyth** [comment]
Yeah I was thinking that the issue would have been related to the version that the provider is using. I will have to put a pin in this for a while, as I'm not good enough with Go to work around it with my own fork, and have it do the updates one at a time via a loop.
