### ISSUE TITLE
In Tree Cinder To CSI Cinder Driver Migration Tracking Issue

### ISSUE THREAD

**Issue by adisky** [kubernetes/cloud-provider-openstack#627]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:
All API Calls to Intree Cinder Driver (https://github.com/kubernetes/kubernetes/tree/master/pkg/volume/cinder) eventually be migrated to cinder CSI Driver (https://github.com/kubernetes/cloud-provider-openstack/tree/master/pkg/csi/cinder), 
For this migration to be successfull, we need to ensure following things
1.  All features in cinder intree driver should be supported by cinder csi driver.
2.  Stability of cinder CSI driver
3.  Cinder Intree E2E tests should pass with migration flags enabled

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/20190129-csi-migration.md
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/csi-migration.md

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jichenjc** [comment]
@adisky  still reading the doc provided, just to confirm my rough understanding, All API Calls need to be handled in k8s then in turn using CSI to talk to our cloud provider ,correct? so we need migrate the major code into CSI (if needed) then create some stubs in tree in order to call CSI, correct?  then with migration flag we can do the e2e test? Thanks

**Comment by adisky** [comment]
@jichenjc We do not need to do these stuff, as all in tree drivers will be migrated to respective CSI drivers the storage community is doing that, we need to make sure about stability/features of CSI driver and Testing with migration flag enabled
https://docs.google.com/document/d/15Q4wXVqbalrVgf_jlGis4QFXN1RY1GMiY-Ek-hpCr-o/edit#

**Comment by jichenjc** [comment]
ok, got it , thanks for the info, I will keep an eye here :)

**Comment by adisky** [comment]
Tested manually static, dynamic provisioning it is working well, run e2e tests but most of the tests require multinode env

**Comment by afritzler** [comment]
Just for my understanding: If I migrate my cluster from an in-tree cloud controller-based to the Cinder CSI out-of-tree controller. Is there anything I need to take care of in my existing cluster? Or will all existing `pv`'s and `pvc`'s be correctly handled by the out-of-tree controller?

**Comment by adisky** [comment]
yes, but is in alpha stage you need to enable some feature gates

**Comment by afritzler** [comment]
Thanks a lot! Is there any documentation out there on how to do that?

I have the following 2 scenarios here:
1. Clusters which are <= 1.14.x which run all in-tree.
2. Starting with >= 1.15.x the OoT CCM for LBs, and KubeControllerManager + Kubelet still on OpenStack in-tree

Now the question is: what do I need to do for existing >= 1.15 cluster when upgrading to the OoT CCM and CSI? I guess if that is solved, I could also migrate the <= 1.14.

**Comment by chrigl** [comment]
To keep this updated. My latest run on a multinode cluster with featureGates CSIMigration and CSIMigrationOpenStack enabled:

```
-ginkgo.focus="\[sig-storage\]\sIn-tree\sVolumes\s\[Driver:\scinder" -ginkgo.skip="\[Disruptive\]|\[Serial\]|\[Feature:.+\]|\[Slow\]"
```

Resulted in:
```
Oct 28 10:30:45 control-plane e2e.test[20947]: Oct 28 10:30:45.241: INFO: Running AfterSuite actions on node 1
Oct 28 10:30:45 control-plane e2e.test[20947]: Ran 20 of 4897 Specs in 950.631 seconds
Oct 28 10:30:45 control-plane e2e.test[20947]: SUCCESS! -- 20 Passed | 0 Failed | 0 Pending | 4877 Skipped
Oct 28 10:30:45 control-plane e2e.test[20947]: PASS
```

I will run another test with Slow included, and will start to create a PR-ify this on openlabs.

**Comment by chrigl** [comment]
@afritzler Just to verify that I understand correct. You are on 1.15+ with oot ccm?

Moving to CSI could be done in multiple steps. But in any case, you must deploy `cinder-csi-plugin`. The CSI plugin and in-tree can live side-by-side, and can be selected by StorageClass.

The thing with CSIMigration (which is still in alpha in 1.16, so be aware!) is: We keep the in-tree API in-tact, but instead of reaching out to the in-tree-cloud-provider-code, the call is translated so CSI. What means, even if you have PVCs with the "old" storage class, the volumes will be handled by Cinder CSI. To achieve this, the following feature-gates must be enabled on `kube-controller-manager`, `kube-apiserver` and `kubelet`:
```
CSIMigration: true
CSIMigrationOpenStack: true
ExpandCSIVolumes: true
```

For more detail see https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/csi-migration.md

**Comment by afritzler** [comment]
Thanks @chrigl for the clarification. So I tried now the migration flags on `kube-api`, `kube-controller-manager` and `kubelet` and set the cloudprovider flag to `external.

It looks like the CSI plugin is taking care of the old PVs. However attaching an old PV to a node fails with the following error:

```
I1129 16:03:30.395660       1 volume_store.go:145] Volume pvc-ff83251d-953e-49b5-8289-6d73805aa53e enqueued
I1129 16:03:31.035958       1 volume_store.go:154] Saving volume pvc-ff83251d-953e-49b5-8289-6d73805aa53e
E1129 16:03:31.038088       1 volume_store.go:144] error saving volume pvc-ff83251d-953e-49b5-8289-6d73805aa53e: persistentvolumes "pvc-ff83251d-953e-49b5-8289-6d73805aa53e" is forbidden
```

What happens actually with the existing `StorageClass`. When I understand the migration document correctly, I won't be able get rid of it in the future.

**Comment by kayrus** [comment]
> error saving volume

it is from the https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/blob/c525773885fccef89a1edd22bb3f813d50548ed1/controller/volume_store.go#L161 and it looks like the [current RBAC](https://github.com/kubernetes/cloud-provider-openstack/blob/f8ad69f78a71f945eef6c0858afecbe68f14c79d/manifests/cinder-csi-plugin/cinder-csi-nodeplugin-rbac.yaml#L16) is not sufficient for this operation, because it covers only event resources.

@ramineni, do Cinder CSI functional tests cover Cinder CSI + RBAC case?

**Comment by ramineni** [comment]
@afritzler which version of k8s are you running ? What is the attacher sidecar version you are running ? Are you using the same rbac manifests located in the repo only ?

**Comment by afritzler** [comment]
In my test setup I am upgrading 1.14.9 -> 1.15.4. Attacher is on version v1.2.1. And yes I was using the manifests from the `manifest` folder. The only thing which is different on the RBAC side is the fact that I am using a dedicated `kubeconfig` and `User` rolebinding instead of a `ServiceAccount`.

**Comment by ramineni** [comment]
@afritzler Is your issue resolved? Existing RBAC in default manifests should be sufficient, hope you are using cluster level role binding to avoid any issue with namespaces. 
I suggest you raise different issue with all the details for easier tracking and help

**Comment by chrigl** [comment]
/close

We have e2e testing with CSIMigration in place: http://status.openlabtesting.org/job/cloud-provider-openstack-multinode-csi-migration-test

Also sorted out issues found during e2e tests.
e.g. #897 and #925 

We extended documentation in #835
