### ISSUE TITLE
 support coreos in CPO

### ISSUE THREAD

**Issue by jichenjc** [kubernetes/cloud-provider-openstack#667]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:

**What you expected to happen**:
coreos has some difference to normal linux like AE is using ignition while normal linux use cloud-init (such as /var/lib/cloud/data/instance-id can't be used ) so need check coreos still work on CPO 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kazesberger** [comment]
**hi, minor prior suggestion:** 
we could remove the volume/mount for /var/lib/cloud/data/ from the daemonset as it is not required since https://github.com/kubernetes/cloud-provider-openstack/pull/331. or maybe provide 2 variants in the manifests folder. shall i open/provide separate issue/pr?

**Details:**
made my first attempts using the csi plugin and noticed, that I had to remove the mount/volume for 
/var/lib/cloud/data/ from the node daemonset so pods did start (the path was missing on my ContainerLinux instances although I'm pretty sure that I've been using cloud-init - ...weird, but didn't look much further into it)
referenced here:
https://github.com/kubernetes/cloud-provider-openstack/blob/e2ab1688e926d606e94e12896402d677338de003/manifests/cinder-csi-plugin/cinder-csi-nodeplugin.yaml#L78
