### ISSUE TITLE
[Cinder CSI] device isn't initialized correctly

### ISSUE THREAD

**Issue by mape90** [kubernetes/cloud-provider-openstack#705]
**What happened**:
In rare cases volume attached to VM might not be initialized correctly by udev. This causes that device do not have volume id specified and plugin can not find the device.

This can be fixed by executing `udevadm trigger` as then volume will get all necessary information.

**What you expected to happen**:
Plugin should try to "rescan" devices so that if udev missed it trigger it would not cause issues.

**How to reproduce it (as minimally and precisely as possible)**:
Huge amount of volume attachments. There aren't any easy way to reproduce this as the root cause isn't clear. 

**Anything else we need to know?**:
Easy fix would be to edit GetDevicePath function in mount.go so that it would  call probeVolume function in case device path could not be found. 
For examble:
```
func (m *Mount) GetDevicePath(volumeID string) (string, error) {
	...
	err := wait.ExponentialBackoff(backoff, func() (bool, error) {
		devicePath = m.getDevicePathBySerialID(volumeID)
		if devicePath != "" {
			return true, nil
		}
		probeVolume() // <-- added line
		return false, nil
	})
        ...
```
There we would only probe volumes if we do not find the volume. 

/kind bug

**Comment by adisky** [comment]
@mape90 could please also share logs, what errors are you getting??

**Comment by mape90** [comment]
Sorry the delay. 

I currently do not have the logs, but what happens is that udev isn't triggered when volume is attached to node. So node_server can never find it as that device do not have the link in /dev/disk/by-id/. 

Actual problem is in host operating system side as it should handle all volume attachment events. However I have seen in many different OS vendors this same issue. 

It is quite rare and it might be automatically resolved if the host gets other volume attachments.

And I think this issue have been seen before as there exits the code to fix this problem. Even it is currently just dead code. However it still has test cases.

**Comment by mape90** [comment]
This scanning was removed at PR https://github.com/kubernetes/cloud-provider-openstack/pull/595 

It was correctly removed as path can not be trusted. However this also removes the probing what then causes these non-initialized volumes.

**Comment by chrischdi** [comment]
Hi,
think we can also see the same issue in an KVM environment using virtio-blk and virtio-scsi.
The fix for us is also as simple as doing a `udevadm trigger` to create the symlink which csi is able to find.

I would be happy to help on this one and am also able to provide logs or other information :-)

**Comment by ramineni** [comment]
@chrischdi Thanks. Feel free to submit PR on the same.

**Comment by zetaab** [comment]
we have seen this same issue in our openstack as well. However, I feel that this is problem with OpenStack side instead of k8s problem. Of course we can make temporary changes to k8s code, but it is not the correct way how it should be handled. 

We are always deploying following script to all nodes:
```
#!/bin/bash

DEFAULTDEVICES=2

while true
do
    DEVICECOUNT=$(ls /dev/vd*|grep -e "/dev/vd[a-z]*$"|wc -l)
    CINDERCOUNT=$((${DEVICECOUNT}-${DEFAULTDEVICES}))
    IDCOUNT=$(ls /dev/disk/by-id/virtio-*|grep -e "/dev/disk/by-id/virtio-[a-z0-9-]"|wc -l)
    if [ "$IDCOUNT" -ne "$CINDERCOUNT" ]; then
        logger "Running udevadm trigger..."
        udevadm trigger
    fi
    sleep 59
done
```

this will fix the issues for us (but sometimes it takes minute or so)

**Comment by chrischdi** [comment]
Can you explain what the problem then is on Openstack side?
Your script does the same in the and like the PR - an `udevadm trigger`.

Could you maybe explain how this could be fixed on Openstack side?

**Comment by zetaab** [comment]
Ok let put it another way: in 80-95% of cases when the new cinder volume is mounted, the serial id is there and kernel udev can see it. However, there are 5-20% cases where the serial id is **NOT** in place when the kernel receives the udev event. 

Is OpenStack planned like that people should manually execute `udevadm trigger` in instances after they have attached volume to their instance. I do not think so. I am pretty sure that this is a bug in some of the OpenStack components / or bug in KVM or something else. I am not OpenStack coder so I do not know how these things work in the background. At least my logic says that volume serial id should be in place either 0% or 100% of attachments, otherwise it is not working like should.
