### ISSUE TITLE
add legacy lbaas v2 in addtion to octavia api for ingress controller

### ISSUE THREAD

**Issue by jenningsloy318** [kubernetes/cloud-provider-openstack#784]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind feature

**What happened**:
Our openstack environment still use legacy lbaas v2 api which can't not upgrade to octavia as hardware restriction, so when deploy kubernetes we can't leverage octavia  ingress controller, thus hope ingress controller also can support neutron lbaas v2 api to create ingress object on our openstack platform. 

**What you expected to happen**:
ingress controller can support legacy lbaas v2 api, then we can use this ingress controller to create ingress on openstack platform 

**How to reproduce it (as minimally and precisely as possible)**:
none

**Anything else we need to know?**:
none
**Environment**:
- openstack-cloud-controller-manager version: 1.15 
- OS (e.g. from /etc/os-release): ubuntu 18.04 
- Kernel (e.g. `uname -a`): Linux k8s-cluster-master-01 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Others:

**Comment by kayrus** [comment]
@jenningsloy318 legacy lbaas v2 is fully supported by the CCM and it is enabled by default. Is it an option for you to use cloud-controller-manager?

**Comment by jenningsloy318** [comment]
I can use openstack-cloud-control-manager successfully, but as you guys mentioned in the octavia ingress controller page ,ingress controller can use one lb with multiple services, but openstack cloud control manager will create one lb for each servicce ,this is costly. So I tried octavia ingress controller , but got error that don’t find octavia endpoint. And really the platform don’t have octavia api support, so  wish in the controller ,it can also support  neutron Lbaas V2EX then I can use this ingress controller. In the config file of octavia ingress controller ,only support octavia options,no neutron options

**Comment by kayrus** [comment]
@jenningsloy318 I'm not a project maintainer, I just contribute a little bit. It's very nice that you pointed to the differences between regular CCM and ingress controller. We also use neutron lbaas and it probably I can introduce the neutron lbaas support to reduce an amount of loadbalancers in our environment.

**Comment by jenningsloy318** [comment]
@kayrus it is very helpful, thanks for your info, can you share some guidelines or doc for it?

**Comment by kayrus** [comment]
@jenningsloy318 there is no much difference between neutron lbaas v2 and octavia API, therefore it is very simple to switch from new package to an old one. The problem is to introduce this support correctly, I need to think about the concept. So far you can easily apply the patch below and compile the binary. Specifying the `use-neutron` in the config should allow you to use legacy API.

```diff
diff --git a/pkg/ingress/config/config.go b/pkg/ingress/config/config.go
index 6d932f0..3e79fdf 100644
--- a/pkg/ingress/config/config.go
+++ b/pkg/ingress/config/config.go
@@ -53,4 +53,8 @@ type octaviaConfig struct {
 	// (Optional) If the ingress controller should manage the security groups attached to the cluster nodes.
 	// Default is false.
 	ManageSecurityGroups bool `mapstructure:"manage-security-groups"`
+
+	// (Optional) If the ingress controller should use legacy neutron lbaas v2 implementation.
+	// Default is false.
+	UseNeutron bool `mapstructure:"use-neutron"`
 }
diff --git a/pkg/ingress/controller/openstack/client.go b/pkg/ingress/controller/openstack/client.go
index 4d9ce99..36348b7 100644
--- a/pkg/ingress/controller/openstack/client.go
+++ b/pkg/ingress/controller/openstack/client.go
@@ -44,11 +44,13 @@ func NewOpenStack(cfg config.Config) (*OpenStack, error) {
 
 	// get octavia service client
 	var lb *gophercloud.ServiceClient
-	lb, err = openstack.NewLoadBalancerV2(provider, gophercloud.EndpointOpts{
-		Region: cfg.OpenStack.Region,
-	})
-	if err != nil {
-		return nil, fmt.Errorf("failed to find octavia endpoint for region %s: %v", cfg.OpenStack.Region, err)
+	if !cfg.Octavia.UseNeutron {
+		lb, err = openstack.NewLoadBalancerV2(provider, gophercloud.EndpointOpts{
+			Region: cfg.OpenStack.Region,
+		})
+		if err != nil {
+			return nil, fmt.Errorf("failed to find octavia endpoint for region %s: %v", cfg.OpenStack.Region, err)
+		}
 	}
 
 	// get neutron service client
@@ -60,6 +62,10 @@ func NewOpenStack(cfg config.Config) (*OpenStack, error) {
 		return nil, fmt.Errorf("failed to find neutron endpoint for region %s: %v", cfg.OpenStack.Region, err)
 	}
 
+	if cfg.Octavia.UseNeutron {
+		lb = network
+	}
+
 	// get nova service client
 	var compute *gophercloud.ServiceClient
 	compute, err = openstack.NewComputeV2(provider, gophercloud.EndpointOpts{

```

**Comment by lingxiankong** [comment]
> @jenningsloy318 there is no much difference between neutron lbaas v2 and octavia API, therefore it is very simple to switch from new package to an old one. The problem is to introduce this support correctly, I need to think about the concept.

It's not as easy as the code you provided I'm afraid. The most important difference is, octavia based ingress controller is importing `openstack/loadbalancer/v2` package in gophercloud, which is totally different with neutron-lbaas (`openstack/networking/v2/extensions/lbaas_v2`). Secondly, the resource model and implementation between octavia and neutron-lbaas have changed a lot after neutron-lbaas was deprecated since Queens release, e.g. the features leveraged in octavia ingress controller that are not supported in neutron-lbaas, including batch update pool members, shared pools etc.

As the upstream community, it's not common to add support to deprecated services or features, but given you are still using neutron-lbaas and don't have a plan to upgrade to octavia, I don't think that should stop you to implement in your own fork.

**Comment by jenningsloy318** [comment]
@kayrus thanks so much,I will patch this and to configure it in our environment

**Comment by kayrus** [comment]
@lingxiankong thanks for your input. I'm aware about these differences.
@jenningsloy318 the initial patch won't work indeed. It requires more modifications.

I'm still thinking about the concept, especially on how to add the flexibility and avoid code duplication.

**Comment by kayrus** [comment]
When I though about the legacy neutron support, it appeared that it requires a lot of the logic copy-paste. Moreover, most of the logic is already written in terraform, e.g.:
* terraform resource dependencies
* cascade resource deletion is not required, because terraform handles this by design
* legacy neutron lbaas_v2 status checks

I also analyzed the current Octavia ingress controller code and noticed, that it doesn't support:
* TLS certificates (`TERMINATED_HTTPS`)
* TCP/UDP listeners (like in [nginx ingress controller](https://github.com/kubernetes/ingress-nginx/blob/2c6fbdca3056c746d9cdd4a59bd90734b4c8c4d7/docs/user-guide/exposing-tcp-udp-services.md))
* Parallelism, when multiple ingress controllers are provisioned.
* Flexibility for an end user, like templating engine in [nginx ingress controller](https://github.com/kubernetes/ingress-nginx/blob/2c6fbdca3056c746d9cdd4a59bd90734b4c8c4d7/docs/user-guide/nginx-configuration/custom-template.md)
* Custom configuration snippets, like in [nginx ingress controller](https://github.com/kubernetes/ingress-nginx/blob/2c6fbdca3056c746d9cdd4a59bd90734b4c8c4d7/docs/user-guide/nginx-configuration/annotations.md#configuration-snippet)
* and more

Considering the written above I decided to develop a one-size-fits-all solution and combine the ingress controller with terraform. Since terraform supports a wide range of cloud providers, it can be used not only for OpenStack, but for all other clouds, which have an LBaaS and a terraform provider.

Terraform is yet another abstraction layer and it adds an overhead comparing to pure gophercloud usage, even with all the cons, the pros outweigh the cons.

https://github.com/kayrus/ingress-terraform
