### ISSUE TITLE
Filter instances ipv4/6 addresses

### ISSUE THREAD

**Issue by yanndegat** [kubernetes/cloud-provider-openstack#89]
/kind feature

**What happened**:
my nodes are identified either by their ipv4 addr or their ipv6, according 
to the numerical order of the adresses.
Once added to the the nodeAddresses list, the type of the addr is lost.

**What you expected to happen**:
something more consistent & at least either ipv4 addrs or ipv6 addrs

**How to reproduce it (as minimally and precisely as possible)**:
setup an openstack network with ipv4 & ipv6 support such as your instances
get 2 addresses.

**Comment by yanndegat** [comment]
would be nice if we could optionally "disable ipv6 support", by filtering ipv6-like addrs before returning
nodeAddresses

**Comment by dims** [comment]
good suggestion! we could easily do a config option. Are you able to help with a PR? since you already have an environment to try things out (we are on kubernetes slack #sig-openstack)

**Comment by dims** [comment]
cc @zioproto

**Comment by zioproto** [comment]
hello @yanndegat 
with the support for networking opts you disabled the IPv6 addresses in Kubernetes and this solves your problem. But, even reading https://github.com/kubernetes/kubernetes/issues/62163 , I did not understand what is the original problem.

Do you have a situation where Openstack assigns to a VM both an IPv4 and an IPv6 address, but the IPv6 address is not actually configured on the VM because for example the operating system does not support it ?

Please clarify if this is the original issue, or if there is another problem I did not understand. 

Instead of disabling IPv6 I would like to fix the actual issue.

thank you

**Comment by kartoch** [comment]
hello @zioproto. At the present time, this is more about stability in production (avoid IPv6) and openstack IPv6 forced configuration.

**Comment by yanndegat** [comment]
hi @zioproto 

there's an issue when an openstack network supports both ipv6 and ipv4
the addresses list returned by the Openstack API doesn't have a "type" attribute to distinguished 
an ipv4 from an ipv6
and furthermore, the kubernetes lib doens't have this attribute either

so that you can end in a situation where your nodes are identified by the "first IP" of addresses
and as the order is alphanum, you can have either an ipv6 or an ipv4

even if you don't want to support ipv6 at all.

one could argue that we should choose another openstack network that doesn't support ipv6
but imagine that this network is the public network, managed by the cloud provider...
this is a dead end scenario, an it's actually the case on at least one openstack public cloud.

**Comment by dims** [comment]
i'd buy the argument by @yanndegat let's close this out

/close
