### ISSUE TITLE
openstack-cloud-controller-manager can not show version

### ISSUE THREAD

**Issue by RainbowMango** [kubernetes/cloud-provider-openstack#907]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**The binaries affected**:
- [x] openstack-cloud-controller-manager

**What happened**:
Invalid version information from `openstack-cloud-controller-manager --version`.
```
[root@ecs-d8b6 cloud-provider-openstack]# make openstack-cloud-controller-manager
CGO_ENABLED=0 GOOS=linux go build \
-ldflags "-w -s -X 'k8s.io/cloud-provider-openstack/pkg/version.Version=v1.17.0-34-asfasd'" \
-o openstack-cloud-controller-manager \
cmd/openstack-cloud-controller-manager/main.go
[root@ecs-d8b6 cloud-provider-openstack]# ./openstack-cloud-controller-manager --version
Kubernetes v0.0.0-master+$Format:%h$
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version: 1.17.0
- OpenStack version: N/A
- Others:

**Comment by RainbowMango** [comment]
cc @dims 
Is this a problem and any idea about it?

**Comment by mikejoh** [comment]
Interesting, could it be due to us calling this function:
https://github.com/kubernetes/cloud-provider-openstack/blob/46cab81a3590238390809ceed942993d796aa50b/cmd/openstack-cloud-controller-manager/main.go#L94 

This code was imported from `k8s.io/kubernetes/pkg/version/verflag`  (pre k8s `1.17.0` at least). So it looks like that our `version.Version` never gets outputted but instead something related to `kubernetes` itself? The `-X` flag is set correctly at compile time and the `version.Version` prints the version set through the `Makefile`.

Bascially we should probably change the way we print the version, maybe use constructs within `cobra`?

**Comment by RainbowMango** [comment]
> So it looks like that our version.Version never gets outputted but instead something related to kubernetes itself?

Yes. The version information comes from Kubernetes. And the information is wrong because of we are build outside of Kubernetes, so no chance to inject version infor to `gitVersion   `.
https://github.com/kubernetes/kubernetes/blob/718714a9359e628d43aa1005301427983b760b59/staging/src/k8s.io/component-base/version/base.go#L58.

**Comment by jichenjc** [comment]
seems the others like cinder-csi-plugin doesn't have this 
should we consider use same pattern for all exec file we compiled ?

**Comment by mikejoh** [comment]
@jichenjc Yes you're correct, the `cinder-csi-plugin` doesn't expose a `--version` flag. Haven't looked through the rest of them though. I think it's a good idea to at least have a way of printing the version and if possible do it in a unified way across all binaries compiled within the `cloud-provider-openstack` project!

**Comment by jichenjc** [comment]
I can help the review since you already have the plan :) thanks a lot

**Comment by ramineni** [comment]
@mikejoh Im assigning this to you , if you don't have plans to fix , pls unassign yourself.
/assign @mikejoh

**Comment by mikejoh** [comment]
@ramineni Thanks! 👍🏻 I will try to fix this one as soon as i’m back from vacation.
