### ISSUE TITLE
report error: Cloud not construct reference to : "&v1.Lease{}'

### ISSUE THREAD

**Issue by xishengcai** [kubernetes/cloud-provider-openstack#956]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>/ just report error, but work well

**The binaries affected**:
- [x] openstack-cloud-controller-manager
**What happened**:
my log report:
E0305 13:49:40.756670    8661 event.go:319] Could not construct reference to: '&v1.Lease{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cloud-controller-manager", GenerateName:"", Namespace:"kube-system", SelfLink:"/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cloud-controller-manager", UID:"57462201-ac24-484a-a44e-af6998729406", ResourceVersion:"716", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63718984180, loc:(*time.Location)(0x2e11d80)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:v1.LeaseSpec{HolderIdentity:(*string)(nil), LeaseDurationSeconds:(*int32)(nil), AcquireTime:(*v1.MicroTime)(nil), RenewTime:(*v1.MicroTime)(nil), LeaseTransitions:(*int32)(nil)}}' due to: 'no kind is registered for the type v1.Lease in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"'. Will not report event: 'Normal' 'LeaderElection' 'xisheng_df0a7c6e-de3d-4c28-8e7a-ecb31dd6503f became leader'

**What you expected to happen**:
I don't want to see this happen

**How to reproduce it**:

**Anything else we need to know?**:
I copy you code to write huawei cloud ccm, when I run it , report this error

**Environment**:
- openstack-cloud-controller-manager version:  master
- OpenStack version: 
 running on huawei ecs
use kubeadm build cluster  kuberente 1.15.3
- Others:
I modify s.Generic.LeaderElection.ResourceLock="endpoints", will not report error

**Comment by lingxiankong** [comment]
Thanks for reporting the issue but we only accept issues related to cloud-provider-openstack, not your own customized code.

For your case, please try a higher version k8s.

/close

**Comment by xishengcai** [comment]
I have tryed on k8s 1.17.0, but always happend.

**Comment by lingxiankong** [comment]
> I have tryed on k8s 1.17.0, but always happend.

Which image are you using for OCCM? Could you paste the configuration of OCCM?

**Comment by yerzhant** [comment]
Have the same issue:

`
E0317 08:01:40.755248       1 event.go:319] Could not construct reference to: '&v1.Lease{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cloud-controller-manager", GenerateName:"", Namespace:"kube-system", SelfLink:"/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/cloud-controller-manager", UID:"2bf34ab4-8c94-4c81-86cb-628be0e80be8", ResourceVersion:"3819", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63720028516, loc:(*time.Location)(0x2cb5f20)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:v1.LeaseSpec{HolderIdentity:(*string)(nil), LeaseDurationSeconds:(*int32)(nil), AcquireTime:(*v1.MicroTime)(nil), RenewTime:(*v1.MicroTime)(nil), LeaseTransitions:(*int32)(nil)}}' due to: 'no kind is registered for the type v1.Lease in scheme "pkg/runtime/scheme.go:101"'. Will not report event: 'Normal' 'LeaderElection' 'master-1_2e20adfd-f6a6-4172-84d4-ee64da965262 became leader'
`

Fresh installation of cluster (v1.17.0) and then OCCM according to [this](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/using-openstack-cloud-controller-manager.md) doc.

`---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: "external"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.17.0
#networking:
#  podSubnet: 192.168.0.0/16
apiServer:
  extraArgs:
    runtime-config: "storage.k8s.io/v1=true"
    cloud-provider: "external"
controllerManager:
  extraArgs:
    cloud-provider: "external"
`

`
auth-url=https://auth.pscloud.io/v3
#Tip: You can also use Application Credential ID and Secret in place of username, password, tenant-id, and domain-id.
#application-credential-id=***
#application-credential-secret=***
username=***
# user-id=
password=***
region=RegionOne
tenant-id=***
domain-id=default
ca-file=/etc/ssl/certs/ca-user-trust.crt

[LoadBalancer]
#use-octavia=true
subnet-id=29c0f0ab-b912-4cf6-8b87-ab7b7c20aef2
floating-network-id=83554642-6df5-4c7a-bf55-21bc74496109

[BlockStorage]
bs-version=v2
`

**Comment by xishengcai** [comment]
I use endpoint  can avoid error.
s.Generic.LeaderElection.ResourceLock="endpoints"

**Comment by lingxiankong** [comment]
@xishengcai I just have installed k8s v1.17.2 and OCCM this morning, didn't see any issue. Are there any special configuration for your k8s?

**Comment by xishengcai** [comment]
my kubernetes install config:

apiVersion: kubeadm.k8s.io/v1beta1
controlPlaneEndpoint: 121.36.221.246:6443 
imageRepository: registry.aliyuncs.com/google_containers
kind: ClusterConfiguration
kubernetesVersion: 1.17.0
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12

install cmd:
kubeadm init --config=/root/kubeadm-config.yaml --upload-certs
