### ISSUE TITLE
create lb failed when only has master nodes on k8s

### ISSUE THREAD

**Issue by xishengcai** [kubernetes/cloud-provider-openstack#978]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**The binaries affected**:

- [ x ] openstack-cloud-controller-manager

**What happened**:
E0318 11:31:52.268315       1 controller.go:243] error processing service default/nginx (will retry): failed to ensure load balancer: there are no available nodes for LoadBalancer service default/nginx

**What you expected to happen**:
create loadbalancer for svc success, but result is "pending".

**How to reproduce it**:
only has master,  and no  slave nodes.

**Anything else we need to know?**:

**Environment**:
- openstack-cloud-controller-manager version:
- OpenStack version:
- Others:

**Comment by lingxiankong** [comment]
> there are no available nodes

I think the message is clear enough for what's going on.

**Comment by chrigl** [comment]
/close

Kubernetes filters nodes by certain rules: See https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/controller.go#L606

It is a good thing that it remains in pending, because the LB will be created as soon as a schedulable and ready node appears (either removing the NoSchedule taint from cp nodes or joining a worker node).
